import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import ImageUploader from '../components/ImageUploader';
import CameraCapture from '../components/CameraCapture';
import ResultCard from '../components/ResultCard';
import { Loader2, RotateCcw, AlertCircle } from 'lucide-react';

export default function Detection() {
  const { t } = useTranslation();
  const [selectedFile, setSelectedFile] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const handleImageSelect = (file, preview) => {
    setSelectedFile(file);
    setImagePreview(preview);
    setResult(null);
    setError(null);
  };

  const handleAnalyze = async () => {
    if (!selectedFile) return;

    setLoading(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append('file', selectedFile);

      const response = await fetch('/api/predict', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        throw new Error('Prediction failed');
      }

      const data = await response.json();

      if (data.success) {
        const predictionWithTimestamp = {
          ...data.prediction,
          timestamp: new Date().toISOString(),
          image: imagePreview,
        };

        setResult(predictionWithTimestamp);

        // Save to history
        const history = JSON.parse(localStorage.getItem('predictions') || '[]');
        history.unshift(predictionWithTimestamp);
        // Keep only last 10
        if (history.length > 10) history.pop();
        localStorage.setItem('predictions', JSON.stringify(history));
      } else {
        throw new Error('Prediction failed');
      }
    } catch (err) {
      setError(err.message || 'Failed to analyze image');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!result) return;

    const text = `
Disease Detection Result
========================
Disease: ${result.disease}
Confidence: ${result.confidence}%
Severity: ${result.severity}

Symptoms:
${result.symptoms?.join('\n') || 'N/A'}

Treatment:
${result.treatment || 'N/A'}

Prevention:
${result.prevention || 'N/A'}

Generated by Sugarcane Disease Detection App
Date: ${new Date(result.timestamp).toLocaleString()}
    `.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `disease-result-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    if (!result) return;

    const text = `Disease: ${result.disease}\nConfidence: ${result.confidence}%\nSeverity: ${result.severity}\n\nSymptoms:\n${result.symptoms?.join('\n') || 'N/A'}\n\nTreatment:\n${result.treatment || 'N/A'}\n\nPrevention:\n${result.prevention || 'N/A'}`;

    try {
      await navigator.clipboard.writeText(text);
      alert('Copied to clipboard!');
    } catch (err) {
      alert('Failed to copy');
    }
  };

  const resetDetection = () => {
    setSelectedFile(null);
    setImagePreview(null);
    setResult(null);
    setError(null);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Header */}
        <div className="text-center mb-10">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
            {t('detection.title')}
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Upload an image or use your camera to detect sugarcane diseases instantly
          </p>
        </div>

        {/* Main Content */}
        {!result ? (
          <div className="max-w-2xl mx-auto">
            {/* Upload Card */}
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8 mb-6">
              <ImageUploader onImageSelect={handleImageSelect} />

              {imagePreview && !loading && (
                <div className="mt-6">
                  <div className="rounded-lg overflow-hidden bg-gray-100 dark:bg-gray-700 mb-4">
                    <img
                      src={imagePreview}
                      alt="Preview"
                      className="w-full h-64 object-contain"
                    />
                  </div>
                  <button
                    onClick={handleAnalyze}
                    className="w-full bg-primary text-white py-4 px-6 rounded-lg text-lg font-semibold hover:bg-secondary transition-all transform hover:scale-[1.02] active:scale-[0.98] shadow-md"
                  >
                    🔍 Analyze Image
                  </button>
                </div>
              )}

              {loading && (
                <div className="mt-6 flex flex-col items-center justify-center py-8 space-y-4">
                  <Loader2 className="w-12 h-12 animate-spin text-primary" />
                  <p className="text-lg font-medium text-gray-700 dark:text-gray-300">
                    {t('detection.analyzing')}
                  </p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Analyzing your image with advanced detection...
                  </p>
                </div>
              )}

              {error && (
                <div className="mt-6 bg-red-50 dark:bg-red-900/20 border-2 border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-4 rounded-lg flex items-center space-x-3">
                  <AlertCircle className="w-5 h-5 flex-shrink-0" />
                  <span>{error}</span>
                </div>
              )}
            </div>

            {/* OR Divider */}
            {!imagePreview && !loading && (
              <>
                <div className="relative my-8">
                  <div className="absolute inset-0 flex items-center">
                    <div className="w-full border-t-2 border-gray-300 dark:border-gray-600"></div>
                  </div>
                  <div className="relative flex justify-center">
                    <span className="px-4 bg-gray-50 dark:bg-gray-900 text-gray-500 font-medium">OR</span>
                  </div>
                </div>

                {/* Camera Card */}
                <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8">
                  <CameraCapture onImageCapture={handleImageSelect} />
                </div>
              </>
            )}
          </div>
        ) : (
          <div className="max-w-4xl mx-auto">
            {/* Result Display */}
            <ResultCard
              result={result}
              image={imagePreview}
              onDownload={handleDownload}
              onCopy={handleCopy}
            />

            {/* Try Another Button */}
            <div className="mt-6 text-center">
              <button
                onClick={resetDetection}
                className="inline-flex items-center space-x-2 bg-gray-600 text-white py-3 px-8 rounded-lg text-lg font-semibold hover:bg-gray-700 transition-all transform hover:scale-[1.02] active:scale-[0.98] shadow-md"
              >
                <RotateCcw className="w-5 h-5" />
                <span>{t('detection.tryAnother')}</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
